name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    name: Build & Test (C++23)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang 22, Tools & libc++
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22 clang-tidy-22 clang-tools-22 libc++-22-dev libc++abi-22-dev
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-22 100
          sudo update-alternatives --set clang /usr/bin/clang-22
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-22 100
          sudo update-alternatives --set clang++ /usr/bin/clang++-22
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-22 100
          sudo update-alternatives --set clang-format /usr/bin/clang-format-22
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-22 100
          sudo update-alternatives --set clang-tidy /usr/bin/clang-tidy-22
          sudo ln -sf /usr/lib/llvm-22/bin/clang-scan-deps /usr/bin/clang-scan-deps

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Configure and build (Debug mode with ASan)
        run: |
          xmake f -y -c -m debug --toolchain=clang --sdk=/usr/lib/llvm-22 --runtimes=c++_shared --ldflags=-lc++abi
          xmake -v

      - name: Lint (format + clang-tidy)
        run: xmake lint

      - name: Run binary
        run: |
          xmake run kravidb

      - name: Run unit tests (Debug, ASan + UBSan)
        run: xmake test

      - name: Configure and build (Release mode)
        run: |
          xmake f -y -c -m release --toolchain=clang --sdk=/usr/lib/llvm-22 --runtimes=c++_shared --ldflags=-lc++abi
          xmake -v

      - name: Run unit tests (Release)
        run: xmake test
